"""make time nullabble in events

Revision ID: 14a248a080ac
Revises: e5882fbda66c
Create Date: 2025-12-11 22:11:24.469719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14a248a080ac"
down_revision: Union[str, None] = "e5882fbda66c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events", "start_time", existing_type=postgresql.TIME(), nullable=True
    )
    op.alter_column(
        "events", "end_time", existing_type=postgresql.TIME(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events", "end_time", existing_type=postgresql.TIME(), nullable=False
    )
    op.alter_column(
        "events", "start_time", existing_type=postgresql.TIME(), nullable=False
    )
    # ### end Alembic commands ###
