"""added events.exclude_admin_report

Revision ID: 190404b2d461
Revises: 4d5f54739bf4
Create Date: 2025-12-19 13:37:05.429856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "190404b2d461"
down_revision: Union[str, None] = "4d5f54739bf4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "exclude_admin_report",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "exclude_admin_report")
    # ### end Alembic commands ###
