"""renamed columns

Revision ID: 2a0fab2e18c1
Revises: 14a248a080ac
Create Date: 2025-12-12 01:13:33.345077

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2a0fab2e18c1"
down_revision: Union[str, None] = "14a248a080ac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_groups", sa.Column("aggregate_task_id", sa.UUID(), nullable=True)
    )
    op.drop_constraint(
        "event_groups_aggregate_publication_task_id_fkey",
        "event_groups",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "event_groups",
        "tasks",
        ["aggregate_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("event_groups", "aggregate_publication_task_id")
    op.alter_column(
        "typed_tasks",
        "due_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.Date(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "typed_tasks",
        "due_date",
        existing_type=sa.Date(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
    )
    op.add_column(
        "event_groups",
        sa.Column(
            "aggregate_publication_task_id",
            sa.UUID(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "event_groups", type_="foreignkey")
    op.create_foreign_key(
        "event_groups_aggregate_publication_task_id_fkey",
        "event_groups",
        "tasks",
        ["aggregate_publication_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_column("event_groups", "aggregate_task_id")
    # ### end Alembic commands ###
