"""added due date to task

Revision ID: 30b75b721412
Revises: 5c1ac0c523e9
Create Date: 2025-09-28 07:09:34.864099

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "30b75b721412"
down_revision: Union[str, None] = "5c1ac0c523e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.add_column("tasks", sa.Column("due_date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "due_date")

