"""removed cascade delete group events

Revision ID: 458818266e18
Revises: 9c509f34dcba
Create Date: 2025-06-15 12:44:49.187613

"""
from  typing import Sequence, Union

from  alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '458818266e18'
down_revision: Union[str, None] = '9c509f34dcba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_constraint('events_group_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'event_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_group_id_fkey', 'events', 'event_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_table('images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    # ### end Alembic commands ###
