"""added tasks.birthday_user_id

Revision ID: 4d5f54739bf4
Revises: f148d17f47e2
Create Date: 2025-12-17 21:45:45.614209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "4d5f54739bf4"
down_revision: Union[str, None] = "f148d17f47e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("birthday_user_id", sa.UUID(), nullable=True))
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.create_foreign_key(
        None, "tasks", "users", ["birthday_user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.alter_column("tasks", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("tasks", "birthday_user_id")
    # ### end Alembic commands ###
