"""added periods tables

Revision ID: 4e674806bc9a
Revises: 30b75b721412
Create Date: 2025-10-12 17:37:38.065903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e674806bc9a'
down_revision: Union[str, None] = '30b75b721412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirements')
    op.drop_column('required_periods', 'user_role')
    op.alter_column('tasks_token', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('tasks_token', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False,
                    existing_server_default=sa.text('now()'))
    op.alter_column('typed_tasks', 'due_date',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('typed_tasks', 'due_date',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True)
    op.alter_column('tasks_token', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.alter_column('tasks_token', 'created_at',
                    existing_type=postgresql.TIMESTAMP(timezone=True),
                    nullable=True,
                    existing_server_default=sa.text('now()'))
    op.add_column('required_periods',
                  sa.Column('user_role', postgresql.ENUM('PHOTOGRAPHER', 'COPYWRITER', 'DESIGNER', name='userrole'),
                            autoincrement=False, nullable=False))
    op.create_table('requirements',
                    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
                    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
                    sa.Column('user_role', postgresql.ENUM('PHOTOGRAPHER', 'COPYWRITER', 'DESIGNER', name='userrole'),
                              autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='requirements_pkey')
                    )
    # ### end Alembic commands ###
