"""added notes tables

Revision ID: 805bdc47fca4
Revises: 91cba09a89be
Create Date: 2025-12-10 04:33:26.155223

"""
from  typing import Sequence, Union

from  alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '805bdc47fca4'
down_revision: Union[str, None] = '91cba09a89be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.create_table(
        'home_notes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column(
            'role',
            ENUM(
                'PHOTOGRAPHER',
                'COPYWRITER',
                'DESIGNER',
                name='userrole',
                create_type=False,  # do NOT emit CREATE TYPE
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'home_files',
        sa.Column('home_note_id', sa.UUID(), nullable=False),
        sa.Column('file_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['home_note_id'], ['home_notes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('home_note_id', 'file_id'),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('home_files')
    op.drop_table('home_notes')
    # ### end Alembic commands ###
