"""removed event group assotiation table

Revision ID: 9c509f34dcba
Revises: d44469cc9a03
Create Date: 2025-06-14 19:59:58.905916

"""
from  typing import Sequence, Union

from  alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9c509f34dcba'
down_revision: Union[str, None] = 'd44469cc9a03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_group_associations')
    op.drop_table('images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_table('event_group_associations',
    sa.Column('event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_group_associations_event_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['event_groups.id'], name='event_group_associations_group_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'group_id', name='event_group_associations_pkey')
    )
    # ### end Alembic commands ###
