"""added custom_achievements table

Revision ID: b015eade0a3b
Revises: bb7c247e89f1
Create Date: 2025-12-20 04:42:10.518980

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "b015eade0a3b"
down_revision: Union[str, None] = "bb7c247e89f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_achievements",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("date_from", sa.Date(), nullable=False),
        sa.Column("date_to", sa.Date(), nullable=True),
        sa.Column("level_of_participation", sa.String(), nullable=True),
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("achievement_level", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_custom_achievements_id"), "custom_achievements", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_custom_achievements_id"), table_name="custom_achievements")
    op.drop_table("custom_achievements")
    # ### end Alembic commands ###
