"""added score to custom_achievements table

Revision ID: c975fca00cf8
Revises: b015eade0a3b
Create Date: 2025-12-22 00:24:24.634547

"""
from  typing import Sequence, Union

from  alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c975fca00cf8'
down_revision: Union[str, None] = 'b015eade0a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_achievements', sa.Column('score', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_achievements', 'score')
    # ### end Alembic commands ###
