"""added name and use_in_pgas  to typed task

Revision ID: cf597eacbb3c
Revises: 6bc441dd3461
Create Date: 2025-12-11 21:06:47.659374

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "cf597eacbb3c"
down_revision: Union[str, None] = "6bc441dd3461"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("typed_tasks", sa.Column("name", sa.String(), nullable=True))
    op.add_column(
        "typed_tasks",
        sa.Column(
            "use_in_pgas", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("typed_tasks", "use_in_pgas")
    op.drop_column("typed_tasks", "name")
    # ### end Alembic commands ###
