"""added aggregate task to group

Revision ID: e5882fbda66c
Revises: cf597eacbb3c
Create Date: 2025-12-11 22:07:41.349614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "e5882fbda66c"
down_revision: Union[str, None] = "cf597eacbb3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "event_groups",
        sa.Column("aggregate_publication_task_id", sa.UUID(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "event_groups",
        "tasks",
        ["aggregate_publication_task_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "event_groups", type_="foreignkey")
    op.drop_column("event_groups", "aggregate_publication_task_id")
    # ### end Alembic commands ###
