"""added tasks.use_in_pgas column

Revision ID: f148d17f47e2
Revises: 2a0fab2e18c1
Create Date: 2025-12-14 01:10:41.614310

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "f148d17f47e2"
down_revision: Union[str, None] = "2a0fab2e18c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column(
            "use_in_pgas", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    op.drop_column("typed_tasks", "use_in_pgas")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "typed_tasks",
        sa.Column(
            "use_in_pgas",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("tasks", "use_in_pgas")
    # ### end Alembic commands ###
