services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - ./uploads/images:/uploads/images
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    env_file:
      - .env
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./db-data:/var/lib/postgresql/data
