FROM tiangolo/uvicorn-gunicorn:python3.11-slim
WORKDIR /usr/src
COPY requirements.txt /tmp/requirements.txt
RUN pip cache purge
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/requirements.txt
