from  tiangolo/uvicorn-gunicorn:python3.10-slim
WORKDIR /app
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt

CMD alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000
