FROM python:3.11-slim
WORKDIR /app
COPY ./requirements.txt /tmp/requirements.txt
RUN pip cache purge
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY . /app/api
ENV PYTHONPATH=.
RUN chmod -R +x /app/api/scripts/*.sh
